// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import consts "github.com/Amazeful/Amazeful-Backend/consts"
import context "context"
import mock "github.com/stretchr/testify/mock"
import options "go.mongodb.org/mongo-driver/mongo/options"
import primitive "go.mongodb.org/mongo-driver/bson/primitive"
import util "github.com/Amazeful/Amazeful-Backend/util"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// FindOne provides a mock function with given fields: ctx, filter, document, opts
func (_m *Repository) FindOne(ctx context.Context, filter primitive.M, document util.Model, opts ...*options.FindOneOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter, document)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, util.Model, ...*options.FindOneOptions) error); ok {
		r0 = rf(ctx, filter, document, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertOne provides a mock function with given fields: ctx, document, opts
func (_m *Repository) InsertOne(ctx context.Context, document util.Model, opts ...*options.InsertOneOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, document)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, util.Model, ...*options.InsertOneOptions) error); ok {
		r0 = rf(ctx, document, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// New provides a mock function with given fields: db, collection
func (_m *Repository) New(_ consts.MongoDatabase, _ consts.MongoCollection) util.Repository {
	return _m
}

// ReplaceOne provides a mock function with given fields: ctx, filter, replacement, opts
func (_m *Repository) ReplaceOne(ctx context.Context, filter primitive.M, replacement util.Model, opts ...*options.ReplaceOptions) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter, replacement)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.M, util.Model, ...*options.ReplaceOptions) error); ok {
		r0 = rf(ctx, filter, replacement, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
